In [2]:
# Use the numpy library
import numpy as np

In [ ]:
def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = None
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = None

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = None

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

In [ ]:
def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    pass
    

In [ ]:
def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    pass

In [3]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])

In [7]:
input_array=np.arange(15).reshape(3, 5)

In [8]:
print("Input as Array: {}".format(input_array))

Input as Array: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print("Input minus min: {}".format(inputs_minus_min))

In [ ]:
print("Input  Array: {}".format(inputs_div_max))

In [ ]:
print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))

In [ ]:
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))

In [ ]:
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

In [2]:
print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: None
Input minus min: None
Input  Array: None
Multiply 1:
None
Multiply 2:
None
Multiply 3:
None
Mean == None


In [3]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [4]:
m
# displays the following result:
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
m.T
# displays the following result:
# array([[ 1,  5,  9],
#        [ 2,  6, 10],
#        [ 3,  7, 11],
#        [ 4,  8, 12]])

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [6]:
m_t = m.T

In [7]:
m_t[3][1] = 200

In [8]:
m_t
# displays the following result:
# array([[ 1,   5, 9],
#        [ 2,   6, 10],
#        [ 3,   7, 11],
#        [ 4, 200, 12]])

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [9]:
m
# displays the following result:
# array([[ 1,  2,  3,   4],
#        [ 5,  6,  7, 200],
#        [ 9, 10, 11,  12]])

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [12]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])

In [13]:
inputs
# displays the following result:
# array([[-0.27,  0.45,  0.64,  0.31]])

array([[-0.27,  0.45,  0.64,  0.31]])

In [14]:
inputs.shape
# displays the following result:
# (1, 4)

(1, 4)

In [15]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [16]:
weights
# displays the following result:
# array([[ 0.02 ,  0.001, -0.03 ,  0.036],
#        [ 0.04 , -0.003,  0.025,  0.009],
#        [ 0.012, -0.045,  0.28 , -0.067]])

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [17]:
weights.shape
# displays the following result:
# (3, 4)

(3, 4)

In [18]:
np.matmul(inputs, weights)
# displays the following error:
# ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [19]:
np.matmul(inputs, weights.T)
# displays the following result:
# array([[-0.01299,  0.00664,  0.13494]])

array([[-0.01299,  0.00664,  0.13494]])

In [24]:
def say_hi(name,age):
    print(" my name is " +name+ "and age is " +str(age))

In [25]:
say_hi("Pankaj", 34)

 my name is Pankajand age is 34


In [31]:
def max_num(num1,num2,num3):
    if num1 > num2 and num1 > num3:
        return num1
    elif num2 > num1 and num2 > num3:
        return num2
    else:
        return num3

In [30]:
max_num(1,2,3)

3

In [32]:
max_num(36,37,21)

37